package com.dinglabs.culturalinterviews

import org.scalatest.FunSuite
import java.io.File

class MainTest extends FunSuite {

  test("extractContentFromHtml") {
    val file = new File("src/test/resources/example_content.html")
    val c = Main.extractContentFromHtml(file)
    assert(c.filename     == "ste08lijie")
    assert(c.speakerName  == "Li, Jie")
    assert(c.location     == "China, Shanghai")
    assert(c.english      == "Concerning Americans, and that they are firm in their opinions or opinionated, I do not see it this way. We Chinese often look at being opinionated from the downside. We call this ‘transcendentalism’. This is a term for us. But in my view, through the projects in which I’ve participated in the US, projects in which I had to cooperate with Americans, I discovered more and more that Americans are not at all opinionated. They are not at all prone to any solid and unchangeable prejudices, and they do not use their tough thinking and ideas to arbitrarily judge a thing or an issue. We can see that a lot of people think this way (about Americans), that they are arbitrary and transcendental or abstract, but this is because they have (too often) communicated with Americans of higher status or advanced age. I don’t feel that this is a problem with the person, but rather a problem with the age group. I feel that especially in the case of young people…younger and younger people in the U.S. are extremely friendly in their associations with others. They will even change their opinions constantly to cater to the opinions of the rest of the world. Thusly, these American young people constantly touring the world, constantly contacting people of various countries, and their ideas and thinking are constantly changing. They are able to accept very new and fresh things and alter their own judgments of things, the way that they judge and the basis of judgment and of certain standards. Therefore I feel that this view of Americans is very one-dimensional and not objective. In my view, the young American friends that I have are all extremely willing to accept new things and change their way of thinking. Thank you.")
    assert(c.pinyin       == "E, guānyú Měiguórén tāmen bǐjiào… e, bǐjiào nà, e yǒu gùdìng de sīxiǎng, wǒ bìngbú zhème rènwéi. Wǒmen Zhōngguórén bǎ gùdìng de sīxiǎng jīngcháng shì fùmiànde kàn, wǒmen chēngzhīwéi xíng’érshàngxué, zhèshi wǒmen de yíge shùyǔ. Dànshì zàiwǒ kànlái, tōngguò wǒ zài, Měiguó cānjiā de yìxiē xiàngmù, hé, Měi, hé Měiguórén zhījiān de hézuò xiàngmù, wǒ yuèláiyuè fāxiàn, Měiguórén qíshí bìng búshì yǒu gùdìng de sīxiǎng, tāmen bìng búhuì, e, yǒu yìxiē gùdìng búbiàn de piānjiàn, yě búhuì yǐ zìjǐ de yìxiē qiángyìng de xiǎngfa hé yìxiē e, sī, sīxiǎng lái pànduàn, wǔduànde pànduàn yíxiàng shìwù, huò yíge, yíge shìqing. Yīnwèi wǒmen kěyǐ kàndao dàduōshùrén yǒu zhèyang de sīxiǎng rènwéi Měiguórén, tāmen bǐjiào wǔduàn, bǐjiào xíng’érshàngxué, shì yīnwèi tāmen hé Měiguó yìxiē bǐjiào niánzhǎngde, hé yìxiē bǐjiào, n…zěnme jiǎng bǐjiào, e, gāo, gāo céngcì derén, gāo, gāo niánlíng de, gāo niánlíngduàn derén jiāoliú. Yīnwèi zhèxiērén, zhèxiē niánlíng derén, tāmen díquè…zhè, zhè, wǒ juéde zhè búshì yìzhǒng…zhè búshì yìzhǒngrén de wèntí, érshì yìzhǒng niánjì hé yìxiē niánlíng de wèntí. Wǒ juéde yóuqíshi xiàng Měiguó yìxiē qīngniánrén hé Měiguó yìxiē yuèláiyuè niánqīng derén, tāmen hé rénmen jiāowǎng zhījiān háishì fēicháng yǒuhǎo, shènzhi tāmen huì búduànde gǎibiàn zìjǐ de sīxiǎng qù yínghé zhěngge shìjiède sīxiǎng. Yóu, suízhe zhèxiē Měiguó niánqīngrén, tāmen búduànde zhōuyóu shìjiè, hé búduànde hé gèguórén jiāotán, tāmende xiǎngfa zài búduànde biànhuà, tāmen kěyǐ jiēshòu hěn xīnxiān de shìwù lái gǎibiàn zìjǐ pànduàn shìwùde, pànduàn shìwùde fāngfǎ hé pànduàn shìwùde yījù hé yìxiē biāozhǔn. Suǒyǐ, wǒ rènwéi duì Měiguórén zhèyang kànfa, qíshíshi bù quánmiàn hé bú kèguān de. Zài wǒ kànlái, wǒde yìxiē Měiguó niánqīng péngyou, tāmen dōu fēicháng yuànyì jiēshòu xīnde shìwu, bìng gǎibiàn zìjǐ de xiǎngfa. Xièxie.")
    assert(c.chinese_simp == "哦关于美国人他们比较…哦、比较那、哦有固定的思想，我并不这么认为。我们中国人把固定的思想经常是负面地看，我们称之为形而上学，这是我们的一个术语。但是在我看来，通过我在、美国参加的一些项目，和美、和美国人之间的合作项目，我越来越发现，美国人其实并不是有固定的思想，他们并不会，哦，有一些固定不变的偏见，也不会以自己的一些强硬的想法和一些哦、思、思想来判断、武断地判断一项事物，或一个、一个事情。因为我们可以看到大多数人有这样的思想认为美国人他们比较武断，比较形而上学，是因为他们和美国一些比较年长的，和一些比较、嗯…怎么讲比较、哦…高、高层次的人，高、高年龄的、高年龄段的人交流。因为这些人、这些年龄的人，他们的确…这、这我觉得这不是一种…这不是一种人的问题，而是一种年纪和一些年龄的问题。我觉得尤其是像美国一些青年人和美国一些越来越年轻的人，他们和人们交往之间还是非常友好，甚至他们会不断地改变自己的思想去迎合整个世界的思想。由、随着这些美国年轻人，他们不断地周游世界，和不断地和各国人交谈，他们的想法在不断地变化，他们可以接受很新鲜的事物来改变自己判断事物的、判断事物的方法和判断事物的依据和一些标准。所以，我认为对美国人这样看法，其实是不全面和不客观的。在我看来，我的一些美国年轻朋友，他们都非常愿意接受新的事物，并改变自己的想法。谢谢。")
    assert(c.chinese_trad == "哦關於美國人他們比較…哦、比較那、哦有固定的思想，我幷不這麽認爲。我們中國人把固定的思想經常是負面地看，我們稱之爲形而上學，這是我們的一個術語。但是在我看來，通過我在、美國參加的一些項目，和美、和美國人之間的合作項目，我越來越發現，美國人其實幷不是有固定的思想，他們幷不會，哦，有一些固定不變的偏見，也不會以自己的一些强硬的想法和一些哦、思、思想來判斷、武斷地判斷一項事物，或一個、一個事情。因爲我們可以看到大多數人有這樣的思想認爲美國人他們比較武斷，比較形而上學，是因爲他們和美國一些比較年長的，和一些比較、嗯…怎麽講比較、哦…高、高層次的人，高、高年齡的、高年齡段的人交流。因爲這些人、這些年齡的人，他們的確…這、這我覺得這不是一種…這不是一種人的問題，而是一種年紀和一些年齡的問題。我覺得尤其是像美國一些青年人和美國一些越來越年輕的人，他們和人們交往之間還是非常友好，甚至他們會不斷地改變自己的思想去迎合整個世界的思想。由、隨著這些美國年輕人，他們不斷地周游世界，和不斷地和各國人交談，他們的想法在不斷地變化，他們可以接受很新鮮的事物來改變自己判斷事物的、判斷事物的方法和判斷事物的依據和一些標準。所以，我認爲對美國人這樣看法，其實是不全面和不客觀的。在我看來，我的一些美國年輕朋友，他們都非常願意接受新的事物，幷改變自己的想法。謝謝。")
  }

}
