package com.dinglabs.culturalinterviews

import org.scalatest.FunSuite
import java.io.File

class MainTest extends FunSuite {

  test("extractContentFromHtml") {
    val file = new File("src/test/resources/example_content.html")
    val c = Main.extractContentFromHtml(file)
    assert(c.filename     == "ste08lijie")
    assert(c.speakerName  == "Li, Jie")
    assert(c.location     == "China, Shanghai")
    assert(c.english      == "Concerning Americans, and that they are firm in their opinions or opinionated, I do not see it this way. We Chinese often look at being opinionated from the downside. We call this ‘transcendentalism’. This is a term for us. But in my view, through the projects in which I’ve participated in the US, projects in which I had to cooperate with Americans, I discovered more and more that Americans are not at all opinionated. They are not at all prone to any solid and unchangeable prejudices, and they do not use their tough thinking and ideas to arbitrarily judge a thing or an issue. We can see that a lot of people think this way (about Americans), that they are arbitrary and transcendental or abstract, but this is because they have (too often) communicated with Americans of higher status or advanced age. I don’t feel that this is a problem with the person, but rather a problem with the age group. I feel that especially in the case of young people…younger and younger people in the U.S. are extremely friendly in their associations with others. They will even change their opinions constantly to cater to the opinions of the rest of the world. Thusly, these American young people constantly touring the world, constantly contacting people of various countries, and their ideas and thinking are constantly changing. They are able to accept very new and fresh things and alter their own judgments of things, the way that they judge and the basis of judgment and of certain standards. Therefore I feel that this view of Americans is very one-dimensional and not objective. In my view, the young American friends that I have are all extremely willing to accept new things and change their way of thinking. Thank you.")
    assert(c.pinyin       == "E, guānyú Měiguórén tāmen bǐjiào… e, bǐjiào nà, e yǒu gùdìng de sīxiǎng, wǒ bìngbú zhème rènwéi. Wǒmen Zhōngguórén bǎ gùdìng de sīxiǎng jīngcháng shì fùmiànde kàn, wǒmen chēngzhīwéi xíng’érshàngxué, zhèshi wǒmen de yíge shùyǔ. Dànshì zàiwǒ kànlái, tōngguò wǒ zài, Měiguó cānjiā de yìxiē xiàngmù, hé, Měi, hé Měiguórén zhījiān de hézuò xiàngmù, wǒ yuèláiyuè fāxiàn, Měiguórén qíshí bìng búshì yǒu gùdìng de sīxiǎng, tāmen bìng búhuì, e, yǒu yìxiē gùdìng búbiàn de piānjiàn, yě búhuì yǐ zìjǐ de yìxiē qiángyìng de xiǎngfa hé yìxiē e, sī, sīxiǎng lái pànduàn, wǔduànde pànduàn yíxiàng shìwù, huò yíge, yíge shìqing. Yīnwèi wǒmen kěyǐ kàndao dàduōshùrén yǒu zhèyang de sīxiǎng rènwéi Měiguórén, tāmen bǐjiào wǔduàn, bǐjiào xíng’érshàngxué, shì yīnwèi tāmen hé Měiguó yìxiē bǐjiào niánzhǎngde, hé yìxiē bǐjiào, n…zěnme jiǎng bǐjiào, e, gāo, gāo céngcì derén, gāo, gāo niánlíng de, gāo niánlíngduàn derén jiāoliú. Yīnwèi zhèxiērén, zhèxiē niánlíng derén, tāmen díquè…zhè, zhè, wǒ juéde zhè búshì yìzhǒng…zhè búshì yìzhǒngrén de wèntí, érshì yìzhǒng niánjì hé yìxiē niánlíng de wèntí. Wǒ juéde yóuqíshi xiàng Měiguó yìxiē qīngniánrén hé Měiguó yìxiē yuèláiyuè niánqīng derén, tāmen hé rénmen jiāowǎng zhījiān háishì fēicháng yǒuhǎo, shènzhi tāmen huì búduànde gǎibiàn zìjǐ de sīxiǎng qù yínghé zhěngge shìjiède sīxiǎng. Yóu, suízhe zhèxiē Měiguó niánqīngrén, tāmen búduànde zhōuyóu shìjiè, hé búduànde hé gèguórén jiāotán, tāmende xiǎngfa zài búduànde biànhuà, tāmen kěyǐ jiēshòu hěn xīnxiān de shìwù lái gǎibiàn zìjǐ pànduàn shìwùde, pànduàn shìwùde fāngfǎ hé pànduàn shìwùde yījù hé yìxiē biāozhǔn. Suǒyǐ, wǒ rènwéi duì Měiguórén zhèyang kànfa, qíshíshi bù quánmiàn hé bú kèguān de. Zài wǒ kànlái, wǒde yìxiē Měiguó niánqīng péngyou, tāmen dōu fēicháng yuànyì jiēshòu xīnde shìwu, bìng gǎibiàn zìjǐ de xiǎngfa. Xièxie.")
    assert(c.chinese_simp == "哦关于美国人他们比较…哦、比较那、哦有固定的思想，我并不这么认为。我们中国人把固定的思想经常是负面地看，我们称之为形而上学，这是我们的一个术语。但是在我看来，通过我在、美国参加的一些项目，和美、和美国人之间的合作项目，我越来越发现，美国人其实并不是有固定的思想，他们并不会，哦，有一些固定不变的偏见，也不会以自己的一些强硬的想法和一些哦、思、思想来判断、武断地判断一项事物，或一个、一个事情。因为我们可以看到大多数人有这样的思想认为美国人他们比较武断，比较形而上学，是因为他们和美国一些比较年长的，和一些比较、嗯…怎么讲比较、哦…高、高层次的人，高、高年龄的、高年龄段的人交流。因为这些人、这些年龄的人，他们的确…这、这我觉得这不是一种…这不是一种人的问题，而是一种年纪和一些年龄的问题。我觉得尤其是像美国一些青年人和美国一些越来越年轻的人，他们和人们交往之间还是非常友好，甚至他们会不断地改变自己的思想去迎合整个世界的思想。由、随着这些美国年轻人，他们不断地周游世界，和不断地和各国人交谈，他们的想法在不断地变化，他们可以接受很新鲜的事物来改变自己判断事物的、判断事物的方法和判断事物的依据和一些标准。所以，我认为对美国人这样看法，其实是不全面和不客观的。在我看来，我的一些美国年轻朋友，他们都非常愿意接受新的事物，并改变自己的想法。谢谢。")
    assert(c.chinese_trad == "哦關於美國人他們比較…哦、比較那、哦有固定的思想，我幷不這麽認爲。我們中國人把固定的思想經常是負面地看，我們稱之爲形而上學，這是我們的一個術語。但是在我看來，通過我在、美國參加的一些項目，和美、和美國人之間的合作項目，我越來越發現，美國人其實幷不是有固定的思想，他們幷不會，哦，有一些固定不變的偏見，也不會以自己的一些强硬的想法和一些哦、思、思想來判斷、武斷地判斷一項事物，或一個、一個事情。因爲我們可以看到大多數人有這樣的思想認爲美國人他們比較武斷，比較形而上學，是因爲他們和美國一些比較年長的，和一些比較、嗯…怎麽講比較、哦…高、高層次的人，高、高年齡的、高年齡段的人交流。因爲這些人、這些年齡的人，他們的確…這、這我覺得這不是一種…這不是一種人的問題，而是一種年紀和一些年齡的問題。我覺得尤其是像美國一些青年人和美國一些越來越年輕的人，他們和人們交往之間還是非常友好，甚至他們會不斷地改變自己的思想去迎合整個世界的思想。由、隨著這些美國年輕人，他們不斷地周游世界，和不斷地和各國人交談，他們的想法在不斷地變化，他們可以接受很新鮮的事物來改變自己判斷事物的、判斷事物的方法和判斷事物的依據和一些標準。所以，我認爲對美國人這樣看法，其實是不全面和不客觀的。在我看來，我的一些美國年輕朋友，他們都非常願意接受新的事物，幷改變自己的想法。謝謝。")
  }

  test("extractContentFromHtml prof10thomas.html") {
    val file = new File("src/test/resources/prof10thomas.html")
    val c = Main.extractContentFromHtml(file)
    assert(c.filename     == "prof10thomas")
    assert(c.speakerName  == "Chiang, Thomas")
    assert(c.location     == "China, Shan Dong")
    assert(c.english      == "Yes, during the production process or the business process, we all hope to maximize the profits to ourselves. Our lives are very short, and if in this way we can acquire greater profits and acquire personal wealth, we can meet our needs in this life. But, with regard to this, we should, in addition to our personal profit, also consider the question of social welfare. Uh, “social welfare” means that when you produce a, a thing, there are not only costs to you personally, but also, perhaps you’ve used up [a portion] of some people’s lives and all kinds, all kinds of steps. Uh, because of this, there’s a so-called “social cost.”\nSuppose these social costs are not, are not taken care of, then we can lower our total costs. In that case, our selling price ought to be lower. So, with regard to the large volume of mainland China’s exports in recent years, these cheap exports, I think this is a problem to which we must pay extremely close attention because after these cheap, cheap ex- exports, the ultimate result is that you, you destroy your domestic production resources. They’re also giving rise to problems with the social environment and the ecology. So, in the future the social costs are extremely high.\nOK, so what I advocate is that we not just look at the costs to you personally. We should also look look at the total social cost. Take a simple example. Look, many underdeveloped nations, such as, like uh, let’s not talk about African nations, let’s say nations like Taiwan and Korea were 10 or 20 years ago. They developed, many, uh, manufacturing industries. These industries were all ones that advanced nations didn’t want to develop,1 so they moved them to backward countries, these more second-tier manufacturing nations to to produce [goods]. In this way, their nations avoided, uh, pollution problems. Now, another way of viewing this is to say that they exported pollution to these other nations.\nSo, I, we think that we need to think about the very long term with regard to employment and pollution. Uh, we need to consider not only how much we produce now, how large our profits are now; we should also consider the long-term benefits to our nation and people. Therefore, these social costs and personal costs are an extremely important issue to consider. Thank you.\n1 Throughout this paragraph, the speaker is using “manufacturing industries” to refer to both the industries and the goods they produce. Consequently, shengchan can here be read as either “produce” or “develop.”")
    assert(c.pinyin       == "Yes, zài zhègè shēngchǎn guòchéng zhōng ne háiyǒu hé qǐyè guòchéng zhōng，wǒmen dōu xīwàng mǎnzú zìjǐ zuìdà de lìrùn。Yīnwéi zhègè wǒmen shēngmìng fēicháng yǒuxiàn，zhèyàng wǒmen de dédào bǐjiào gāo de lìrùn ne, dédào gèrén cáifù de huà，kěyǐ mǎnzú wǒmen zhè yīshēng de xūyào。Kěshì zhè fāngmiàn ne chúle ah gèrén de lìrùn，wǒmen yìnggāi xiǎngdào yīgè shèhuì de fú lì de wèn tí。Ah suǒwèi shèhuì fúlì，jiùshìshuō nǐ shēngchǎn yīgè ah yīgè dōngxī，nà búdàn shì yǒu zìjǐ de chéngběn, yěhuì yěxǔ huì xiāohào dào shèhuì qítārén de ah shēnghuó gēn gèzhǒng gèzhǒng ah bùdiào。Ah yīnwéi zhèyàng de guānxì jiù yǒu yīgè suǒwèi shèhuì chéngběn zài lǐmiàn。Suǒyǐ wǒmen kǎolǜ de wèntí，búdànshì gèrén chéngběn yěyào shèhuì chéngběn。\nZhègè shèhuì chéngběn jiǎrú méiyǒu méiyǒu zhàogù de huà，wǒmen jiùhuì bǎ wǒmen zhěnggè chéngběn ne ah dīgū le，nà zhèyàng de huà jiù juéde wǒmen màide jiàgé yìnggāi bǐjiào piányí。Suǒyǐ zhègè duì xiànzài zhōngguó dàlù jiù shuō zuìjìn chūkǒu hěnduō, yǐ liánjià chūkǒu láijiǎng，wǒjuéde zhègèshì yìnggāi fēicháng zhùyì de yīgè wèntí。Yīnwéi lián liánjià shū shūchū yǐhòu, zuìhòu jiéguǒ ne jiù huì nǐ nǐ pòhuài guónèi de shēngchǎn zīyuán。érqiě háiyǒu shèhuì huánjìng，háiyǒu shēngtài de wèntí。Nà zhèyàng ne，yǐhòu zhègè shèhuì chéngběn shì fēichánggāo de。\nOk， suǒyǐ wǒde zhǔzhāng jiùshìshuō wǒmen bù zhǐshì kàn gèrén chéngběn，yìnggāi gèng kàn kàndào kàndào zhěnggè shèhuì chéngběn。Yīgè hěn jiǎndān de lìzi，nǐkàn，hěnduō luòhòu guójiā bǐrúshuō xiàng ē ē ē qítā fēizhōu guójiā búyào tánle，jiùxiàng guòqù ē 10，20 nián xiàng táiwān hánguó zhèxiē guójiā。Tāmen ē shēngchǎn hěnduō suǒwèi āi zhìzàoyè。Zhè zhìzàoyè dōushì xiānjìn guójiā búyào shēngchǎn，nádào luòhòuguó zhèxiē bǐjiào cìyījí de shēngchǎn guójiā qù qù zuò shēngchǎn。Zhèyàng ne tāmen guónèi jiù méiyǒu suǒwèi de ah nàgè wūrǎn de wèntí。Nà cóng lìngwài fāngmiàn ne，zhèxiē wūrǎn jiù shūchū dào qí tā zhè iē guójiā lái。\nSuǒyǐ wǒ wǒmen juédé duì duì zài jiùyè huò wūrǎn zhè fāngmiàn wǒmen yào zuò yīgè fēicháng ah chángqī de kǎolǜ。Ah, yào kǎolǜ de búdàn shì xiànzài wǒmen shēngchǎn duōshǎo dédào duōshǎo lìyì，jiù cóng chángqī láijiǎng yìnggāi kǎolǜ dào duì zìjǐ guójiā mínzú háiyǒu wèilái de de lìyì。Suǒyǐ zhègè ah shèhuì chéngběn gēn gèrén chéngběn shì fēicháng zhòngyào de yīgè kètí yào kǎolǜ de。Xièxiè！")
    assert(c.chinese_simp == "Yes,在这个生产过程中呢还有和企业过程中，我们都希望满足自己最大的利润。因为这个我们生命非常有限，这样我们的得到比较高的利润呢,得到个人财富的话，可以满足我们这一生的需要。可是这方面呢除了啊个人的利润，我们应该想到一个社会的福利的问题。啊所谓社会福利，就是说你生产一个啊一个东西，那不但是有自己的成本,也会也许会消耗到社会其他人的啊生活跟各种各种啊步调。啊因为这样的关系就有一个所谓社会成本在里面。所以我们考虑的问题，不但是个人成本也要社会成本。\n这个社会成本假如没有没有照顾的话，我们就会把我们整个成本呢啊低估了，那这样的话就觉得我们卖的价格应该比较便宜。所以这个对现在中国大陆就说最近出口很多,以廉价出口来讲，我觉得这个是应该非常注意的一个问题。因为廉廉价输输出以后,最后结果呢就会你你破坏国内的生产资源。而且还有社会环境，还有生态的问题。那这样呢，以后这个社会成本是非常高的。\nOk， 所以我的主张就是说我们不只是看个人成本，应该更看看到看到整个社会成本。一个很简单的例子，你看，很多落后国家比如说象哦哦哦其他非洲国家不要谈了，就象过去哦10，20年象台湾韩国这些国家。他们哦生产很多所谓哎制造业。这制造业都是先进国家不要生产，拿到落后国这些比较次一级的生产国家去去做生产。这样呢他们国内就没有所谓的啊那个污染的问题。那从另外方面呢，这些污染就输出到其他这些国家来。\n所以我我们觉得对对在就业或污染这方面我们要做一个非常啊长期的考虑。啊要考虑的不但是现在我们生产多少得到多少利益，就从长期来讲应该考虑到对自己国家民族还有未来的的利益。所以这个啊社会成本跟个人成本是非常重要的一个课题要考虑的。谢谢！")
    assert(c.chinese_trad == "Yes,在這個生產過程中呢還有和企業過程中，我們都希望滿足自己最大的利潤。因為這個我們生命非常有限，這樣我們的得到比較高的利潤呢,得到個人財富的話，可以滿足我們這一生的需要。可是這方面呢除了啊個人的利潤，我們應該想到一個社會的福利的問題。啊所謂社會福利，就是說你生產一個啊一個東西，那不但是有自己的成本,也會也許會消耗到社會其他人的啊生活跟各種各種啊步調。啊因為這樣的關係就有一個所謂社會成本在裏面。所以我們考慮的問題，不但是個人成本也要社會成本。\n這個社會成本假如沒有沒有照顧的話，我們就會把我們整個成本呢啊低估了，那這樣的話就覺得我們賣的價格應該比較便宜。所以這個對現在中國大陸就說最近出口很多,以廉價出口來講，我覺得這個是應該非常注意的一個問題。因為廉廉價輸輸出以後,最後結果呢就會你你破壞國內的生產資源。而且還有社會環境，還有生態的問題。那這樣呢，以後這個社會成本是非常高的。\nOk， 所以我的主張就是說我們不只是看個人成本，應該更看看到看到整個社會成本。一個很簡單的例子，你看，很多落後國家比如說象哦哦哦其他非洲國家不要談了，就象過去哦10，20年象臺灣韓國這些國家。他們哦生產很多所謂哎製造業。這製造業都是先進國家不要生產，拿到落後國這些比較次一級的生產國家去去做生產。這樣呢他們國內就沒有所謂的啊那個污染的問題。那從另外方面呢，這些污染就輸出到其他這些國家來。\n所以我我們覺得對對在就業或污染這方面我們要做一個非常啊長期的考慮。啊要考慮的不但是現在我們生產多少得到多少利益，就從長期來講應該考慮到對自己國家民族還有未來的的利益。所以這個啊社會成本跟個人成本是非常重要的一個課題要考慮的。謝謝！")
  }

}
